module.exports = {
  projects: [
    '<rootDir>/apps/admin',
    '<rootDir>/libs/theme',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/libs/admin/agencies/data-access',
    '<rootDir>/libs/admin/agencies/feature',
    '<rootDir>/libs/admin/shared/view-models',
    '<rootDir>/libs/admin/shell',
    '<rootDir>/libs/utils/testing',
    '<rootDir>/libs/admin/shared/ui-components',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/utils/data-transformation',
    '<rootDir>/libs/utils/form-validators',
    '<rootDir>/libs/user/data-access',
    '<rootDir>/libs/user/store',
    '<rootDir>/libs/user/utils',
    '<rootDir>/libs/user/permissions',
    '<rootDir>/libs/shared/notifications/toasts',
    '<rootDir>/libs/shared/google-analytics',
  ],
};
