
name: PR checks

on:
  pull_request:
    branches:
      - trunk

env: # https://stackoverflow.com/questions/59867124/how-can-i-access-github-action-environment-variables-within-a-bash-script-run-by
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Cypress
        id: cypress-cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v1-${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-cache-v1-${{ runner.os }}
      - name: Install Cypress
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npm i cypress@latest --save-dev
      - name: Run end to end tests
        # run: npx nx run-many --target=e2e --all --headless --parallel --prod --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        run: npm run e2e:admin:ci -- --prod --parallel --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node12-
      - name: Install dependencies
        # https://github.com/actions/cache/issues/193
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run unit tests
        run: npx nx run-many --target=test --all --parallel --maxParallel=5 --bail=1
